---

manifest_file: papers_manifest.yml
accept:
  - Apache-2.0 # Use of Apache conditioned upon no contribution of modified code back to original author/open source community.
  - MIT
  - ISC
  - BSD-2-Clause-FreeBSD
  - BSD-2-Clause-NetBSD
  - BSD-2-Clause
  - BSD-3-Clause-Attribution
  - BSD-3-Clause-Clear
  - BSD-3-Clause-LBNL
  - BSD-3-Clause
  - BSD-4-Clause-UC
  - BSD-4-Clause
  - BSD-Protection
  - MS-PL
  - Ruby # Use of Ruby conditioned upon selection of the BSDL option for any internal/non-source-available modifications.
  - ISC
  - CC0-1.0

reject:
  - AGPL-1.0
  - AGPL-3.0
  - GPL-2.0-with-GCC-exception # Certain GPL licenses have a Classpath exception that we have accepted in limited circumstances because it enable us to put it under our closed, proprietary license.
  - GPL-2.0-with-autoconf-exception
  - GPL-2.0-with-bison-exception
  - GPL-2.0-with-classpath-exception
  - GPL-2.0-with-font-exception
  - GPL-2.0
  - GPL-3.0-with-GCC-exception
  - GPL-3.0-with-autoconf-exception
  - GPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0
  - Artistic-1.0-Perl
  - Artistic-1.0-cl8
  - Artistic-1.0
  - Artistic-2.0
  - MPL-2.0
  - CDDL-1.0
  - CDDL-1.1
  - EPL-1.0

exceptions:
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/args
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/data/event
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/data/inventory
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/data/metric
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/integration
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/log
  - github.com/newrelic/nri-postgresql/vendor/github.com/newrelic/infra-integrations-sdk/persist

