name: Prerelease pipeline

on:
  release:
    types:
      - prereleased
    tags:
      - 'v*'

jobs:
  pre-release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_pre_release.yaml@v2
    with:
      tag: ${{ github.event.release.tag_name }}
      integration: "postgresql"
    secrets: inherit
