name: Trigger prerelease creation

# This workflow triggers a prerelease creation with changelog and the release notes created by the release toolkit.
# This workflow should be triggered merely from the default branch.
# For more details about how to release follow https://github.com/newrelic/coreint-automation/blob/main/docs/release_runbook.md

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 1"

jobs:
  prerelease:
    uses: newrelic/coreint-automation/.github/workflows/reusable_trigger_prerelease.yaml@v2
    with:
      rt-included-files: go.mod,go.sum,build/Dockerfile
    secrets:
      bot_token: ${{ secrets.COREINT_BOT_TOKEN }}
      slack_channel:  ${{ secrets.COREINT_SLACK_CHANNEL }}
      slack_token: ${{ secrets.COREINT_SLACK_TOKEN }}
